import React from "react";
import {
  FileTextIcon,
  DownloadIcon,
  Share2Icon,
  CalendarIcon,
  CheckCircleIcon,
} from "lucide-react";

export default function ReportsArchivePage() {
  const reports = [
    {
      id: 1,
      title: "Hallucination Mitigation in RAG vs Agentic Systems",
      workspace: "GenAI Research",
      date: "2026-03-24",
      citations: 12,
      confidence: "96%",
    },
    {
      id: 2,
      title: "Distributed Caching Architectures using Redis & Qdrant",
      workspace: "System Design",
      date: "2026-03-20",
      citations: 8,
      confidence: "92%",
    },
    {
      id: 3,
      title: "Stateful Multi-Agent Workflows with LangGraph",
      workspace: "Agentic Design",
      date: "2026-03-15",
      citations: 15,
      confidence: "94%",
    },
  ];

  return (
    <div className="flex-1 p-6 overflow-y-auto bg-[#070d19] space-y-6">
      <div className="border-b border-[#152642] pb-4 flex justify-between items-center">
        <div>
          <h1 className="text-lg font-bold text-slate-100">
            Synthesis Reports Archive
          </h1>
          <p className="text-xs text-slate-400">
            Deep literature reviews and executive summaries generated by your
            Report Agent.
          </p>
        </div>
        <button className="bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold text-xs px-3.5 py-2 rounded-xl transition shadow-lg shadow-cyan-600/20 cursor-pointer">
          + New Research Synthesis
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {reports.map((rep) => (
          <div
            key={rep.id}
            className="border border-[#152642] bg-[#091222]/80 rounded-xl p-5 flex flex-col justify-between hover:border-cyan-500/50 transition duration-200 group"
          >
            <div className="space-y-3">
              <div className="flex justify-between items-start">
                <span className="text-[10px] font-mono bg-[#0e1a30] text-cyan-400 border border-cyan-500/30 px-2 py-0.5 rounded">
                  {rep.workspace}
                </span>
                <span className="flex items-center gap-1 text-[11px] text-emerald-400 font-mono font-semibold">
                  <CheckCircleIcon size={12} /> {rep.confidence}
                </span>
              </div>

              <h3 className="text-sm font-bold text-slate-200 group-hover:text-cyan-300 transition leading-snug">
                {rep.title}
              </h3>

              <div className="flex items-center gap-4 text-xs text-slate-500 pt-2 border-t border-[#152642]/60">
                <span className="flex items-center gap-1">
                  <CalendarIcon size={12} /> {rep.date}
                </span>
                <span>• {rep.citations} Sources Cited</span>
              </div>
            </div>

            <div className="flex items-center gap-2 pt-4 mt-4 border-t border-[#152642]">
              <button className="flex-1 flex items-center justify-center gap-1.5 bg-[#0e1a30] hover:bg-slate-800 text-slate-200 border border-[#1e355a] text-xs font-semibold py-2 rounded-lg transition cursor-pointer">
                <DownloadIcon size={14} className="text-cyan-400" /> Export PDF
              </button>
              <button
                title="Share Link"
                className="p-2 bg-[#0e1a30] hover:bg-slate-800 text-slate-400 hover:text-slate-200 border border-[#1e355a] rounded-lg transition cursor-pointer"
              >
                <Share2Icon size={14} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
