import os
import json
from typing import TypedDict, Dict, Any
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END
from langchain_community.tools import DuckDuckGoSearchRun

class ReportState(TypedDict):
  topic:str
  outline:list[str]
  current_section_idx:int
  completed_sections: Dict[str,str]
  final_report_markdown:str
  
llm = ChatGoogleGenerativeAI(
  model="gemini-2.5-flash",
  temperature=0.4,
  google_api_key = os.getenv("GEMINI_API_KEY")
)

search_tool = DuckDuckGoSearchRun()

def planner_node(state: ReportState) -> Dict[str, Any]:
    """
    ACTOR 1: THE PLANNER
    Breaks a broad topic down into a list of specific sub-topics/sections.
    """
    print(f"📋 [PLANNER] Creating research outline for topic: {state['topic']}...")
    
    prompt = f"""You are an elite Research Director. 
    The user wants a highly detailed report on: "{state['topic']}".
    Break this topic down into exactly 3 chronological or logical section headings.
    
    Return ONLY a valid JSON list of strings representing the section titles.
    Example format: ["1. Introduction to X", "2. Technical Architecture of Y", "3. Future Outlook"]"""
    
    response = llm.invoke([HumanMessage(content=prompt)])
    try:
        clean_json = response.content.replace("```json", "").replace("```", "").strip()
        outline = json.loads(clean_json)
    except Exception:
        # Robust fallback mechanism
        outline = [f"1. Executive Summary of {state['topic']}", "2. Comprehensive Analysis", "3. Strategic Recommendations"]
        
    print(f"📋 [PLANNER] Generated Outline: {outline}")
    return {"outline": outline, "current_section_idx": 0, "completed_sections": {}}
  
def writer_node(state: ReportState) -> Dict[str, Any]:
    """
    ACTOR 2: THE SECTION WRITER
    Researches and writes a deep, exhaustive analysis for the current section.
    """
    idx = state["current_section_idx"]
    current_section_title = state["outline"][idx]
    print(f"✍️ [WRITER] Researching and drafting Section {idx + 1}/{len(state['outline'])}: {current_section_title}...")
    
    # Perform a deep web search specific to this individual section
    try:
        search_query = f"{state['topic']} {current_section_title}"
        facts = search_tool.invoke(search_query)
    except Exception:
        facts = "No live data retrieved for this section. Proceeding with standard baseline knowledge."
        
    prompt = f"""You are a specialized Technical Technical Writer. 
    Write a long-form, deeply detailed section for a major research report.
    
    OVERALL REPORT TOPIC: {state['topic']}
    CURRENT SECTION TITLE: {current_section_title}
    FOUNDATIONAL NEWS/FACTS FOUND: {facts}
    
    Provide comprehensive context, technical details, and analyses. Do not skip details. 
    Write using clean Markdown formatting without adding full report titles or document headers."""
    
    response = llm.invoke([HumanMessage(content=prompt)])
    
    # Update our key-value state for sections safely
    updated_sections = dict(state.get("completed_sections", {}))
    updated_sections[current_section_title] = response.content
    
    return {
        "completed_sections": updated_sections,
        "current_section_idx": idx + 1
    }
    
def reviewer_node(state: ReportState) -> Dict[str, Any]:
    """
    ACTOR 3: THE REVIEWER / COMPILER
    Stitches all sections together, fixes formatting, and injects a Table of Contents.
    """
    print("✨ [REVIEWER] Aggregating sections into executive deliverable...")
    
    compiled_body = ""
    for title, content in state["completed_sections"].items():
        compiled_body += f"\n\n## {title}\n\n{content}\n"
        
    full_markdown = f"""# Deep-Dive Research Report: {state['topic']}
*Generated by Autonomous Multi-Agent Workspace Engine*

---

## Table of Contents
"""
    for title in state["outline"]:
        full_markdown += f"- [{title}](#{title.lower().replace(' ', '-').replace('.', '')})\n"
        
    full_markdown += f"\n---{compiled_body}"
    
    print("🏆 [REVIEWER] Final report packaging complete.")
    return {"final_report_markdown": full_markdown}
  
def writing_loop_router(state: ReportState) -> str:
    """
    Determines if the writer needs to process more sections or send it to the reviewer.
    """
    if state["current_section_idx"] < len(state["outline"]):
        return "writer"
    return "reviewer"
 
 
workflow = StateGraph(ReportState)

workflow.add_node("planner", planner_node)
workflow.add_node("writer", writer_node)
workflow.add_node("reviewer", reviewer_node)

workflow.set_entry_point("planner")
workflow.add_edge("planner", "writer")

# Conditional loop back to writer until all outline items are cleared
workflow.add_conditional_edges(
    "writer",
    writing_loop_router,
    {
        "writer": "writer",
        "reviewer": "reviewer"
    }
)
workflow.add_edge("reviewer", END)

report_generation_agent = workflow.compile()